### 新增
POST {{baseUrl}}/thingGroup
Authorization: {{authToken}}
Content-Type: application/json

{
  "title": "变优秀计划"
}


### 分组分页
GET {{baseUrl}}/thingGroup/page?page=1&perPage=150
Authorization: {{authToken}}

### 删除
DELETE {{baseUrl}}/thingGroup/4
Authorization: {{authToken}}

### 成员
GET {{baseUrl}}/thingGroup/members/4
Authorization: {{authToken}}


###事情列表
GET {{baseUrl}}/thing/page?page=1&perPage=10&thingGroupId=5
Authorization: {{authToken}}
